### ISSUE TITLE
ReferenceError: mode is not defined

### ISSUE THREAD

**Issue by baptistapedro** [fuzzitdev/jsfuzz#4]
I have a pretty basic fuzzer and when I try to run it, I have this error

```
/home/nasa/core-js/fuzzers/mesgfuzz.js:1
var cov_2mys8hqaoz=function(){var path="/home/nasa/core-js/fuzzers/mesgfuzz.js";var hash="c7226559dfd6d640358a29d7b757fc0622e37524";var global=new Function("return this")();var gcv="__coverage__";var coverageData={path:"/home/nasa/core-js/fuzzers/mesgfuzz.js",statementMap:{"0":{start:{line:1,column:15},end:{line:1,column:40}},"1":{start:{line:4,column:4},end:{line:12,column:5}},"2":{start:{line:5,column:23},end:{line:7,column:22}},"3":{start:{line:9,column:8},end:{line:9,column:42}},"4":{start:{line:11,column:8},end:{line:11,column:15}},"5":{start:{line:16,column:0},end:{line:16,column:23}}},fnMap:{"0":{name:"fuzz",decl:{start:{line:3,column:15},end:{line:3,column:19}},loc:{start:{line:3,column:24},end:{line:13,column:1}},line:3}},branchMap:{},s:{"0":0,"1":0,"2":0,"3":0,"4":0,"5":0},f:{"0":0},b:{},_coverageSchema:"43e27e138ebf9cfc5966b082cf9a028302ed4184",hash:"c7226559dfd6d640358a29d7b757fc0622e37524"};var coverage=global[gcv]||(global[gcv]={});if(coverage[path]&&co

ReferenceError: mode is not defined
    at Object.<anonymous> (/home/nasa/core-js/fuzzers/mesgfuzz.js:1:1390)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Module.replacementCompile (/usr/lib/node_modules/jsfuzz/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.<anonymous> (/usr/lib/node_modules/jsfuzz/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/jsfuzz/build/src/worker.js:74:22)
```
Any idea what is it about?

**Comment by yevgenypats** [comment]
Did you manage to solve this issue?
